export interface StaticQuestion {
  id: string;
  topic: string | null;
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
  difficulty: 'EASY' | 'MEDIUM' | 'HARD';
  codeSnippet?: string | null;
}

export interface StaticCourse {
  id: string;
  name: string;
  slug: string;
  description: string;
  icon: string;
  color: string;
  badge: string;
  category: 'frontend' | 'backend' | 'database' | 'devops';
  topics: string[];
  questionCount: number;
  questions: StaticQuestion[];
}

// 1. HTML Questions (Curated Track)
const htmlQuestions: StaticQuestion[] = [
  {
    id: 'html-1',
    topic: 'Basic Structure',
    question: 'Which tag serves as the root container for an HTML document?',
    options: ['<body>', '<head>', '<html>', '<title>'],
    correctAnswer: 2,
    explanation: 'The <html> tag wraps all page content and sub-tags as the root node.',
    difficulty: 'EASY',
  },
  {
    id: 'html-2',
    topic: 'Document Setup',
    question: 'What is the primary purpose of the <!DOCTYPE html> declaration?',
    options: [
      'To apply bold styling to body text',
      'To inform the browser that the document is HTML5',
      'To define the webpage title in the tab bar',
      'To link an external stylesheet file',
    ],
    correctAnswer: 1,
    explanation: '<!DOCTYPE html> instructs browsers to render the page in standard HTML5 mode.',
    difficulty: 'EASY',
  },
  {
    id: 'html-3',
    topic: 'Metadata',
    question: 'Where is machine-readable metadata (not displayed directly on screen) placed?',
    options: ['<head>', '<body>', '<footer>', '<main>'],
    correctAnswer: 0,
    explanation: 'The <head> section houses metadata, title, link tags, and script tags.',
    difficulty: 'EASY',
  },
  {
    id: 'html-4',
    topic: 'Semantics',
    question: 'Which semantic element should encapsulate the main navigational links of a website?',
    options: ['<menu>', '<nav>', '<header>', '<aside>'],
    correctAnswer: 1,
    explanation: '<nav> is specifically designated for major site navigation blocks.',
    difficulty: 'EASY',
  },
  {
    id: 'html-5',
    topic: 'Forms & Inputs',
    question: 'Which HTML attribute specifies where to send form data when the form is submitted?',
    options: ['method', 'target', 'action', 'href'],
    correctAnswer: 2,
    explanation: 'The action attribute contains the URL of the script or endpoint that handles form submission.',
    difficulty: 'MEDIUM',
  },
  {
    id: 'html-6',
    topic: 'Accessibility',
    question: 'What is the purpose of the alt attribute on an <img> tag?',
    options: [
      'To provide alternative text for screen readers or broken image links',
      'To define image resolution scale',
      'To specify tooltip text on hover',
      'To animate image loading transitions',
    ],
    correctAnswer: 0,
    explanation: 'alt text is critical for accessibility and describes the visual content when images fail to load.',
    difficulty: 'EASY',
  },
  {
    id: 'html-7',
    topic: 'Modern Features',
    question: 'Which attribute makes an <input> field automatically receive keyboard focus on page load?',
    options: ['autofocus', 'active', 'focused', 'select'],
    correctAnswer: 0,
    explanation: 'autofocus places the cursor in that input field automatically when the document loads.',
    difficulty: 'EASY',
  },
  {
    id: 'html-8',
    topic: 'Semantics',
    question: 'Which HTML5 element represents content indirectly related to the main content, like sidebars or quotes?',
    options: ['<section>', '<article>', '<aside>', '<div>'],
    correctAnswer: 2,
    explanation: '<aside> represents content tangentially related to the surrounding content (sidebars, callouts).',
    difficulty: 'MEDIUM',
  },
  {
    id: 'html-9',
    topic: 'SEO & Meta',
    question: 'Which meta tag configuration ensures responsive scaling across mobile devices?',
    options: [
      '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
      '<meta name="responsive" content="true">',
      '<meta name="screen" content="mobile">',
      '<meta name="scale" content="100%">',
    ],
    correctAnswer: 0,
    explanation: 'The viewport meta tag matches screen width and initial zoom scale for modern mobile viewports.',
    difficulty: 'EASY',
  },
  {
    id: 'html-10',
    topic: 'HTML Tables',
    question: 'Which tag groups the header content in an HTML table for styling and accessibility?',
    options: ['<th>', '<thead>', '<top>', '<tableheader>'],
    correctAnswer: 1,
    explanation: '<thead> encapsulates the header row(s) in a semantic HTML table.',
    difficulty: 'MEDIUM',
  },
];

// 2. CSS Questions (Curated Track)
const cssQuestions: StaticQuestion[] = [
  {
    id: 'css-1',
    topic: 'Flexbox',
    question: 'Which CSS property defines how flex items are aligned along the cross-axis?',
    options: ['justify-content', 'align-items', 'flex-direction', 'align-content'],
    correctAnswer: 1,
    explanation: 'align-items controls cross-axis alignment, while justify-content controls main-axis alignment.',
    difficulty: 'EASY',
  },
  {
    id: 'css-2',
    topic: 'CSS Grid',
    question: 'What does the CSS Grid fractional unit (1fr) represent?',
    options: [
      '1 frame per second',
      'A fraction of the available free space in the grid container',
      'A fixed 100px column width',
      'The font-size ratio',
    ],
    correctAnswer: 1,
    explanation: 'fr units distribute remaining unoccupied space in CSS Grid containers proportionally.',
    difficulty: 'EASY',
  },
  {
    id: 'css-3',
    topic: 'Specificity',
    question: 'Which selector has the highest CSS specificity value?',
    options: ['div.container p', '#main-content', 'button:hover', 'p::first-line'],
    correctAnswer: 1,
    explanation: 'ID selectors (#id) have a specificity weight of (1, 0, 0), overriding classes, attributes, and tags.',
    difficulty: 'MEDIUM',
  },
  {
    id: 'css-4',
    topic: 'Box Model',
    question: 'When box-sizing: border-box is applied, what does the width property include?',
    options: [
      'Content only',
      'Content + Padding + Border',
      'Content + Margin',
      'Content + Padding + Margin',
    ],
    correctAnswer: 1,
    explanation: 'border-box makes width and height encompass content, padding, and border, avoiding overflow bugs.',
    difficulty: 'EASY',
  },
  {
    id: 'css-5',
    topic: 'Positioning',
    question: 'An element with position: absolute is placed relative to:',
    options: [
      'The browser viewport window always',
      'Its closest ancestor with a position other than static',
      'Its immediate parent regardless of positioning',
      'The bottom of the document',
    ],
    correctAnswer: 1,
    explanation: 'Absolute positioning positions an element relative to its nearest positioned ancestor.',
    difficulty: 'MEDIUM',
  },
  {
    id: 'css-6',
    topic: 'Modern CSS',
    question: 'Which CSS function allows math calculations combining different units like 100% - 32px?',
    options: ['math()', 'calc()', 'eval()', 'compute()'],
    correctAnswer: 1,
    explanation: 'calc() performs arithmetic calculations across mixed CSS units.',
    difficulty: 'EASY',
  },
  {
    id: 'css-7',
    topic: 'Variables',
    question: 'How do you retrieve the value of a custom CSS variable (--primary-color)?',
    options: ['get(--primary-color)', 'var(--primary-color)', '$primary-color', 'prop(--primary-color)'],
    correctAnswer: 1,
    explanation: 'var(--variable-name) reads the CSS custom property value.',
    difficulty: 'EASY',
  },
  {
    id: 'css-8',
    topic: 'Responsive Design',
    question: 'Which CSS media feature targets users who have requested dark color themes in their OS?',
    options: [
      'prefers-color-scheme: dark',
      'color-mode: dark',
      'theme: dark',
      'system-theme: night',
    ],
    correctAnswer: 0,
    explanation: 'prefers-color-scheme: dark detects system dark mode preferences.',
    difficulty: 'MEDIUM',
  },
  {
    id: 'css-9',
    topic: 'Glassmorphism',
    question: 'Which CSS property applies a blur filter to the background behind an element?',
    options: ['filter: blur(10px)', 'backdrop-filter: blur(10px)', 'background-blur: 10px', 'surface-blur: 10px'],
    correctAnswer: 1,
    explanation: 'backdrop-filter blurs everything behind the element, creating glassmorphism effects.',
    difficulty: 'MEDIUM',
  },
  {
    id: 'css-10',
    topic: 'Animations',
    question: 'Which property ensures that an animation retains its ending state after completing?',
    options: ['animation-fill-mode: forwards', 'animation-direction: end', 'animation-play-state: paused', 'animation-persist: true'],
    correctAnswer: 0,
    explanation: 'animation-fill-mode: forwards applies the properties calculated by the final keyframe indefinitely.',
    difficulty: 'HARD',
  },
];

// 3. JavaScript Questions (Curated Track)
const jsQuestions: StaticQuestion[] = [
  {
    id: 'js-1',
    topic: 'Scopes & Hoisting',
    question: 'What is the output of typeof null in JavaScript?',
    options: ['"null"', '"undefined"', '"object"', '"boolean"'],
    correctAnswer: 2,
    explanation: 'Due to a historical bug in JavaScript early implementation, typeof null returns "object".',
    difficulty: 'EASY',
  },
  {
    id: 'js-2',
    topic: 'Equality',
    question: 'What does the expression 0.1 + 0.2 === 0.3 evaluate to in JavaScript?',
    options: ['true', 'false', 'NaN', 'TypeError'],
    correctAnswer: 1,
    explanation: 'IEEE 754 floating-point representation causes 0.1 + 0.2 to equal ~0.30000000000000004, not exactly 0.3.',
    difficulty: 'MEDIUM',
  },
  {
    id: 'js-3',
    topic: 'Closures',
    question: 'What is a closure in JavaScript?',
    options: [
      'A method to close browser tabs',
      'A function bundled together with references to its lexical environment',
      'A syntax error in arrow functions',
      'An object with closed prototype links',
    ],
    correctAnswer: 1,
    explanation: 'A closure gives an inner function access to variables from an enclosing outer function scope even after it has returned.',
    difficulty: 'MEDIUM',
  },
  {
    id: 'js-4',
    topic: 'Event Loop',
    question: 'In which order will Promise.then, setTimeout(..., 0), and console.log execute in micro/macro queues?',
    options: [
      'console.log -> Promise.then -> setTimeout',
      'setTimeout -> Promise.then -> console.log',
      'Promise.then -> setTimeout -> console.log',
      'console.log -> setTimeout -> Promise.then',
    ],
    correctAnswer: 0,
    explanation: 'Synchronous console.log runs first, then microtask queue (Promise.then), then macrotask queue (setTimeout).',
    difficulty: 'HARD',
  },
  {
    id: 'js-5',
    topic: 'ES6+ Features',
    question: 'Which array method returns a brand new array with only elements that satisfy a condition?',
    options: ['map()', 'filter()', 'reduce()', 'find()'],
    correctAnswer: 1,
    explanation: 'filter() creates a shallow copy of an array containing only elements that pass the predicate test.',
    difficulty: 'EASY',
  },
  {
    id: 'js-6',
    topic: 'Prototypes',
    question: 'How do you check if an object possesses a direct property not inherited from its prototype chain?',
    options: [
      'Object.hasOwn(obj, "prop")',
      'obj.isDirect("prop")',
      'obj.in("prop")',
      'Object.propertyExists(obj, "prop")',
    ],
    correctAnswer: 0,
    explanation: 'Object.hasOwn() is the modern ES2022 standard replacement for obj.hasOwnProperty().',
    difficulty: 'MEDIUM',
  },
  {
    id: 'js-7',
    topic: 'Immutability',
    question: 'Which method creates a true deep copy of standard serializable objects in modern JS?',
    options: ['structuredClone()', 'Object.assign()', 'JSON.copy()', '{...obj}'],
    correctAnswer: 0,
    explanation: 'structuredClone() performs a deep clone supporting circular references, Maps, Sets, and Dates.',
    difficulty: 'MEDIUM',
  },
  {
    id: 'js-8',
    topic: 'Promises',
    question: 'What does Promise.allSettled() do compared to Promise.all()?',
    options: [
      'Rejects immediately on first error',
      'Waits for all promises to resolve or reject, returning an array of all outcomes',
      'Only executes sequential promises',
      'Returns only the fastest promise',
    ],
    correctAnswer: 1,
    explanation: 'Promise.allSettled() never short-circuits on rejection and returns status and values for all promises.',
    difficulty: 'HARD',
  },
  {
    id: 'js-9',
    topic: 'Operators',
    question: 'What is the key difference between the nullish coalescing operator (??) and logical OR (||)?',
    options: [
      '?? only falls back for null or undefined, whereas || falls back for any falsy value (0, false, "")',
      '?? is faster than || in loops',
      '|| only works on strings',
      'They are completely identical',
    ],
    correctAnswer: 0,
    explanation: '?? preserves falsy values like 0 or empty strings and only falls back when the left operand is null or undefined.',
    difficulty: 'MEDIUM',
  },
  {
    id: 'js-10',
    topic: 'Strict Mode',
    question: 'What happens in strict mode ("use strict") when assigning to an undeclared variable?',
    options: [
      'It silently creates a global variable',
      'It throws a ReferenceError',
      'It converts it to undefined',
      'It produces a console warning',
    ],
    correctAnswer: 1,
    explanation: 'Strict mode prevents accidental globals by throwing a ReferenceError on assignment to undeclared variables.',
    difficulty: 'EASY',
  },
];

// 4. React Questions (Curated Track)
const reactQuestions: StaticQuestion[] = [
  {
    id: 'react-1',
    topic: 'Hooks',
    question: 'Which React hook is used to persist mutable values across renders without triggering a re-render?',
    options: ['useState', 'useRef', 'useEffect', 'useMemo'],
    correctAnswer: 1,
    explanation: 'useRef returns a mutable object whose .current property persists without triggering re-renders when mutated.',
    difficulty: 'EASY',
  },
  {
    id: 'react-2',
    topic: 'Reactivity',
    question: 'When does the cleanup function returned inside useEffect execute?',
    options: [
      'Only when the browser tab closes',
      'Before the effect runs again and when the component unmounts',
      'After every DOM repaint unconditionally',
      'Only when an uncaught error occurs',
    ],
    correctAnswer: 1,
    explanation: 'React runs the returned cleanup function before re-executing the effect and upon component unmount.',
    difficulty: 'MEDIUM',
  },
  {
    id: 'react-3',
    topic: 'Reconciliation',
    question: 'Why is using array index as a key prop in dynamic lists considered an anti-pattern?',
    options: [
      'Keys must be strings only',
      'Index keys cause component state bugs when items are reordered, inserted, or removed',
      'React throws a runtime compile error',
      'It slows down server-side rendering',
    ],
    correctAnswer: 1,
    explanation: 'Reordering list items with index keys causes React to match wrong component state to DOM elements.',
    difficulty: 'MEDIUM',
  },
  {
    id: 'react-4',
    topic: 'Performance',
    question: 'What is the main use case of the useCallback hook?',
    options: [
      'To cache the calculated return value of an expensive calculation',
      'To memoize a callback function instance between renders to prevent unnecessary child re-renders',
      'To run code asynchronously in Web Workers',
      'To replace useState for form inputs',
    ],
    correctAnswer: 1,
    explanation: 'useCallback returns a memoized version of the callback function that only changes if its dependencies change.',
    difficulty: 'MEDIUM',
  },
  {
    id: 'react-5',
    topic: 'React 19 & Server Components',
    question: 'What is a key benefit of React Server Components (RSC)?',
    options: [
      'They can use useState and useEffect directly',
      'Zero client JavaScript bundle size for dependencies consumed purely on the server',
      'They only run in local browser memory',
      'They disable caching completely',
    ],
    correctAnswer: 1,
    explanation: 'Server Components stay on the server, allowing direct database access with zero client-side JS overhead.',
    difficulty: 'HARD',
  },
];

// 5. TypeScript Questions (Curated Track)
const tsQuestions: StaticQuestion[] = [
  {
    id: 'ts-1',
    topic: 'Type System',
    question: 'What is the difference between any and unknown in TypeScript?',
    options: [
      'They are identical aliases',
      'unknown is type-safe; you must perform type narrowing before accessing properties on it',
      'any requires explicit runtime assertions',
      'unknown can only hold primitive strings and numbers',
    ],
    correctAnswer: 1,
    explanation: 'unknown forces developers to verify the type before performing operations, making it the type-safe counterpart of any.',
    difficulty: 'MEDIUM',
  },
  {
    id: 'ts-2',
    topic: 'Utility Types',
    question: 'Which built-in utility type makes all properties of an interface optional?',
    options: ['Partial<T>', 'Required<T>', 'Readonly<T>', 'Pick<T>'],
    correctAnswer: 0,
    explanation: 'Partial<T> constructs a type with all properties of T set to optional (?).',
    difficulty: 'EASY',
  },
  {
    id: 'ts-3',
    topic: 'Generics',
    question: 'How do you constrain a generic type parameter T so that it must have a length property?',
    options: [
      '<T extends { length: number }>',
      '<T implements length>',
      '<T : HasLength>',
      '<T is Array>',
    ],
    correctAnswer: 0,
    explanation: 'Using the extends keyword restricts the generic type T to types that conform to the shape.',
    difficulty: 'MEDIUM',
  },
  {
    id: 'ts-4',
    topic: 'Type Narrowing',
    question: 'Which operator checks if a specific property exists on an object union for type discrimination?',
    options: ['has', 'in', 'contains', 'matches'],
    correctAnswer: 1,
    explanation: 'The in operator narrows down union types by checking for the presence of a property key.',
    difficulty: 'EASY',
  },
  {
    id: 'ts-5',
    topic: 'Advanced Types',
    question: 'What does the never type represent in TypeScript?',
    options: [
      'A value that can be null or undefined',
      'The type of values that never occur (e.g. functions that throw errors or infinite loops)',
      'A synonym for void',
      'An untyped JavaScript function',
    ],
    correctAnswer: 1,
    explanation: 'never represents the empty type: values that never occur, such as exhausted union cases or functions that never return.',
    difficulty: 'HARD',
  },
];

// 6. Python Questions (Curated Track)
const pythonQuestions: StaticQuestion[] = [
  {
    id: 'py-1',
    topic: 'Data Structures',
    question: 'Which data structure in Python is ordered, immutable, and written with parentheses?',
    options: ['list', 'tuple', 'set', 'dictionary'],
    correctAnswer: 1,
    explanation: 'Tuples are ordered, immutable sequences defined using parentheses (e.g. (1, 2, 3)).',
    difficulty: 'EASY',
  },
  {
    id: 'py-2',
    topic: 'Functions & Generators',
    question: 'What keyword turns a Python function into a generator iterator?',
    options: ['return', 'yield', 'generator', 'emit'],
    correctAnswer: 1,
    explanation: 'yield pauses function execution and emits a value to the caller, resuming on the next iteration.',
    difficulty: 'MEDIUM',
  },
  {
    id: 'py-3',
    topic: 'List Comprehensions',
    question: 'What is the output of [x**2 for x in range(4) if x % 2 != 0]?',
    options: ['[0, 1, 4, 9]', '[1, 9]', '[1, 4]', '[0, 4]'],
    correctAnswer: 1,
    explanation: 'range(4) yields 0, 1, 2, 3. The odd numbers are 1 and 3. Their squares are 1 and 9.',
    difficulty: 'MEDIUM',
  },
  {
    id: 'py-4',
    topic: 'OOP',
    question: 'What is the purpose of the __init__ method in a Python class?',
    options: [
      'To import required modules',
      'To initialize an instantiated object with instance variables',
      'To define class-level static properties',
      'To destroy the object upon exit',
    ],
    correctAnswer: 1,
    explanation: '__init__ is the constructor method called automatically when creating a new instance of a class.',
    difficulty: 'EASY',
  },
  {
    id: 'py-5',
    topic: 'Advanced Python',
    question: 'What is the GIL (Global Interpreter Lock) in CPython?',
    options: [
      'A security protocol preventing file system access',
      'A mutex that allows only one native thread to execute Python bytecode at once',
      'An automated memory garbage collector',
      'A debugger tool in the standard library',
    ],
    correctAnswer: 1,
    explanation: 'The GIL prevents true multi-core CPU parallelism for threads within a single CPython process.',
    difficulty: 'HARD',
  },
];

// 7. SQL Questions (Curated Track)
const sqlQuestions: StaticQuestion[] = [
  {
    id: 'sql-1',
    topic: 'Filtering & Aggregations',
    question: 'Which SQL clause is used to filter rows after an aggregate function (COUNT, SUM, AVG) has been applied?',
    options: ['WHERE', 'HAVING', 'GROUP BY', 'ORDER BY'],
    correctAnswer: 1,
    explanation: 'HAVING filters grouped rows after aggregation, while WHERE filters individual rows before grouping.',
    difficulty: 'EASY',
  },
  {
    id: 'sql-2',
    topic: 'Joins',
    question: 'Which type of JOIN returns all records from the left table and matched records from the right table?',
    options: ['INNER JOIN', 'LEFT JOIN', 'RIGHT JOIN', 'CROSS JOIN'],
    correctAnswer: 1,
    explanation: 'LEFT JOIN returns all rows from the left table with NULL values for unmatched right table rows.',
    difficulty: 'EASY',
  },
  {
    id: 'sql-3',
    topic: 'Indexes',
    question: 'What is the primary trade-off of adding multiple indexes to a database table?',
    options: [
      'Queries become slower',
      'Faster SELECT query performance, but slower INSERT, UPDATE, and DELETE operations',
      'Foreign keys stop functioning',
      'Table size is reduced',
    ],
    correctAnswer: 1,
    explanation: 'Indexes speed up lookups but add overhead to write operations because indexes must be updated on each write.',
    difficulty: 'MEDIUM',
  },
  {
    id: 'sql-4',
    topic: 'Transactions',
    question: 'What does the ACID acronym stand for in relational database transactions?',
    options: [
      'Accuracy, Consistency, Integrity, Durability',
      'Atomicity, Consistency, Isolation, Durability',
      'Availability, Concurrency, Indexing, Delivery',
      'Authentication, Cryptography, Identity, Data',
    ],
    correctAnswer: 1,
    explanation: 'ACID guarantees database transactions are processed reliably.',
    difficulty: 'MEDIUM',
  },
  {
    id: 'sql-5',
    topic: 'Window Functions',
    question: 'Which SQL clause is required when invoking a window function like ROW_NUMBER() or RANK()?',
    options: ['OVER ()', 'WINDOW ()', 'PARTITION ()', 'GROUP ()'],
    correctAnswer: 0,
    explanation: 'Window functions use the OVER clause to specify partitioning and ordering across row sets.',
    difficulty: 'HARD',
  },
];

// 8. Git & GitHub Questions (Curated Track)
const gitQuestions: StaticQuestion[] = [
  {
    id: 'git-1',
    topic: 'Branching',
    question: 'Which Git command creates a new branch and switches to it in one step?',
    options: ['git branch -c <name>', 'git checkout -b <name>', 'git merge <name>', 'git switch -m <name>'],
    correctAnswer: 1,
    explanation: 'git checkout -b <name> (or git switch -c <name>) creates and switches to the specified branch.',
    difficulty: 'EASY',
  },
  {
    id: 'git-2',
    topic: 'Staging & Commits',
    question: 'Which command safely records staged snapshot changes into local Git repository history?',
    options: ['git push', 'git add', 'git commit', 'git status'],
    correctAnswer: 2,
    explanation: 'git commit saves staged snapshots into the project timeline.',
    difficulty: 'EASY',
  },
  {
    id: 'git-3',
    topic: 'Rebase vs Merge',
    question: 'What is the main difference between git merge and git rebase?',
    options: [
      'merge creates a merge commit preserving history; rebase rewrites commits onto a new base creating a linear history',
      'rebase is only for deleting remote branches',
      'merge cannot resolve conflicts',
      'They execute the exact same operation under the hood',
    ],
    correctAnswer: 0,
    explanation: 'rebase replays commits on top of another branch for a cleaner linear log, while merge combines branches with a merge commit.',
    difficulty: 'MEDIUM',
  },
  {
    id: 'git-4',
    topic: 'Undoing Changes',
    question: 'Which command temporarily stashes uncommitted modifications so you can switch branches cleanly?',
    options: ['git stash', 'git pause', 'git hide', 'git shelve'],
    correctAnswer: 0,
    explanation: 'git stash temporarily shelves changes in the working directory so you can work on something else.',
    difficulty: 'EASY',
  },
  {
    id: 'git-5',
    topic: 'Remote Repositories',
    question: 'Which command downloads remote commits and branches without automatically merging them into your current branch?',
    options: ['git pull', 'git fetch', 'git clone', 'git checkout'],
    correctAnswer: 1,
    explanation: 'git fetch updates remote tracking branches without touching your working copy, whereas git pull fetches and merges.',
    difficulty: 'MEDIUM',
  },
];

// Master Course Catalog Definition
export const FALLBACK_COURSES: StaticCourse[] = [
  {
    id: 'course-html',
    name: 'HTML',
    slug: 'html',
    description: 'Modern semantic HTML5: document architecture, forms, accessible elements, meta SEO, and multimedia standards.',
    icon: 'FileCode',
    color: 'from-orange-500 to-amber-600',
    badge: 'Frontend Core',
    category: 'frontend',
    topics: ['Document Structure', 'Semantic Elements', 'Forms & Inputs', 'Accessibility (a11y)', 'SEO Metadata'],
    questionCount: 60,
    questions: htmlQuestions,
  },
  {
    id: 'course-css',
    name: 'CSS',
    slug: 'css',
    description: 'Modern responsive CSS: Flexbox, CSS Grid, custom properties, pseudo-selectors, glassmorphism, and animations.',
    icon: 'Palette',
    color: 'from-blue-500 to-indigo-600',
    badge: 'Styling & Design',
    category: 'frontend',
    topics: ['Flexbox', 'CSS Grid', 'Box Model & Specificity', 'Transitions & Keyframes', 'Responsive Media Queries'],
    questionCount: 60,
    questions: cssQuestions,
  },
  {
    id: 'course-js',
    name: 'JavaScript',
    slug: 'javascript',
    description: 'Deep core JavaScript: closures, prototypes, Event Loop, asynchronous Promises, DOM manipulation, and modern ES6+.',
    icon: 'Sparkles',
    color: 'from-amber-400 to-yellow-600',
    badge: 'Language Core',
    category: 'frontend',
    topics: ['Closures & Scope', 'Prototypes & Classes', 'Event Loop & Promises', 'Array Methods', 'ES6+ Modules'],
    questionCount: 60,
    questions: jsQuestions,
  },
  {
    id: 'course-react',
    name: 'React',
    slug: 'react',
    description: 'Component architecture: hooks (useState, useEffect, useMemo), custom hooks, reconciliation, context, and RSC.',
    icon: 'Atom',
    color: 'from-cyan-400 to-blue-600',
    badge: 'UI Framework',
    category: 'frontend',
    topics: ['Component Lifecycle', 'State & Hooks', 'Reconciliation & Keys', 'Context API', 'Server Components'],
    questionCount: 50,
    questions: reactQuestions,
  },
  {
    id: 'course-ts',
    name: 'TypeScript',
    slug: 'typescript',
    description: 'Static type systems: interfaces, type aliases, generics, union discrimination, utility types, and strict compilation.',
    icon: 'Code2',
    color: 'from-blue-600 to-cyan-500',
    badge: 'Typed JS',
    category: 'frontend',
    topics: ['Interfaces vs Types', 'Generics & Constraints', 'Union Narrowing', 'Utility Types', 'Strict Configuration'],
    questionCount: 50,
    questions: tsQuestions,
  },
  {
    id: 'course-py',
    name: 'Python',
    slug: 'python',
    description: 'Python programming: mutable/immutable data structures, generators, list comprehensions, OOP, and decorators.',
    icon: 'Terminal',
    color: 'from-emerald-500 to-teal-600',
    badge: 'Backend & Data',
    category: 'backend',
    topics: ['Data Structures', 'Comprehensions', 'OOP & Classes', 'Generators & Yield', 'Decorators & Exceptions'],
    questionCount: 50,
    questions: pythonQuestions,
  },
  {
    id: 'course-sql',
    name: 'SQL',
    slug: 'sql',
    description: 'Relational database querying: SELECT, multi-table JOINs, GROUP BY aggregations, window functions, and indexing.',
    icon: 'Database',
    color: 'from-purple-500 to-indigo-600',
    badge: 'Databases',
    category: 'database',
    topics: ['Filtering & WHERE', 'JOIN Operations', 'GROUP BY & HAVING', 'Indexes & Keys', 'Transactions & ACID'],
    questionCount: 50,
    questions: sqlQuestions,
  },
  {
    id: 'course-git',
    name: 'Git & GitHub',
    slug: 'git',
    description: 'Version control mastery: branches, rebasing vs merging, staging, commit conventions, remotes, and pull requests.',
    icon: 'GitBranch',
    color: 'from-rose-500 to-orange-500',
    badge: 'Version Control',
    category: 'devops',
    topics: ['Branching & Checkout', 'Commits & History', 'Rebase vs Merge', 'Stashing Changes', 'Remote Collaboration'],
    questionCount: 50,
    questions: gitQuestions,
  },
];

/**
 * Fast lookup map by course slug
 */
export const FALLBACK_COURSES_BY_SLUG = new Map<string, StaticCourse>(
  FALLBACK_COURSES.map((course) => [course.slug, course])
);
